version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" 
    schedule:
      interval: "daily" 
    commit-message:
      prefix: "daily-deps"
    pull-request-branch-name:
      separator: "_"
    target-branch: "master"
